- hosts: container
  become: yes  # become
  tasks:
  - name: webserver is installed
    package:
     name: nginx
     state: present
  - name: webserver is up
    service:
     name: nginx
     state: started
  - name: webserver directory exist
    file:
     path: "{{item}}"
     state: directory
    loop:
     - /var/www/html
     - /usr/share/nginx/html
  - name: static website is deployed
    uri:
     url: https://raw.githubusercontent.com/abdennour/example-static-website/ansible-course/index.html
     dest: /usr/share/nginx/html # /var/www/html
