- name: play to generate SPEC report
  hosts: all
  tasks:
   - name: report is generated
     copy:
      content: |  # note the pipe | is a filterd
       Distribution: {{ ansible_facts.distribution }}
       Distribution Release: {{ ansible_facts.distribution_release }}
       Distribution Version: {{ ansible_facts.distribution_version }}
       Nbre CPU core: {{ ansible_facts.processor_cores }}
       Total Memory: {{ ansible_facts.memtotal_mb }}
      dest: /tmp/specs.report
