- hosts: containers,other_containers
  become: yes
  vars:
   webserver: nginx
   webserver_root_dir: /usr/share/nginx/html
  tasks:
  - name: webserver is installed
    package:
     name: "{{ webserver }}"
     state: present
  - name: webserver is up
    service:
      name: "{{ webserver }}"
      state: started
  - name: webserver root directory exists
    file:
     path: "{{ webserver_root_dir }}"
     state: directory
  - name: static website is deployed
    uri:
     # note gitbranch is defined in the inventory file
     url: https://raw.githubusercontent.com/abdennour/example-static-website/{{ git_branch }}/index.html
     dest: "{{ webserver_root_dir }}"
  - name: login page is deployed
    uri:
      # U can test it with "curl localhost/login.html inside the container
      url: https://raw.githubusercontent.com/abdennour/example-static-website/{{ git_branch }}/login.html
      dest: "{{ webserver_root_dir }}" 
    when: git_branch == 'ansible-course' # note the when condition
